apiVersion: v1
kind: Deployment
metadata:
  name: hellonode
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: hellonode
    spec:
      containers:
      - name: hellonode-pod
        image: deksharag/hellonode:latest
        ports: 
        - containerPort: 8000
        - containerPort: 443
---
apiVersion: v2
kind: Service
metadata:
  name: hellonode-service
spec:
  selector:
    app: hellonode
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
