apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellonode
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellonode
  template:
    metadata:
      labels:
        app: hellonode
    spec:
      containers:
      - name: hellonode-pod
        image: deksharag/hellonode:latest
        ports: 
        - containerPort: 8000
        
---
apiVersion: v1
kind: Service
metadata:
  name: hellonode-service
spec:
  selector:
    app: hellonode
  ports:
  - name: http1
    protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer
